include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - directives_ordering
    - prefer_const_constructors
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - use_key_in_widget_constructors

formatter:
  trailing_commas: preserve
