name: flutter_auto_mappr_example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  custom_lint: ^0.7.5
  cupertino_icons: ^1.0.8

  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  http_cache_hive_store: ^5.0.1
  intl: ^0.20.2
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  sizer: ^3.0.5
  intl_utils: ^2.8.10
  go_router: ^16.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
